### ISSUE TITLE
Kostra projektu

### ISSUE THREAD

**Issue by repli2dev** [InstruktoriBrno/tmou-web#1]
Založení repozitáře se zprovozněným následujícím:
- [x] Nette aplikace
- [x] Doctrine ORM
- [x] Nextras Forms (dodatečné typy form inputů)
- [x] Nettrine Migrations (pro systematické automatizované migrování databázového schématu)
- [x] Ublaboo DataGrid (pro rychlé vytváření administračních tabulek)
- [x] DebugBar MailPanel (pro testování/zachytávání e-mailů v testovacím provozu)
- [x] ReCaptcha integrace (dřív nebo později si nás boti najdou, jako si našli InterLoS).
- [x] League CSV knihovna (pro práci s CSV soubory).
- [x] Adminer (pro připojení k DB)
- [x] Základní chybové stránky
- [x] Dokumentace s detaily jak zprovoznit na lokálním počítači a jak nasadit na produkci.

Ideálně taktéž zprovoznit kontrolu následujícími nástroji:
- [x] PHPStan (statická analýza, umí odchytit řadu problémů plynoucích z dynamičnosti jazyka)
- [x] PHP Code Sniffer (pro zařízení jednotného code style)
- [x] Integrace s Travis CI pro automatizované kontroly

Strávený čas:
- 15m (4. dubna 2019)
- 90m (4. dubna 2019)
- 90m (6. dubna 2019)
- 30m (13. dubna 2019)

**Comment by repli2dev** [comment]
S tou Travis CI kontrolou se ukázalo, že je to spíš otázka licenční... Pro open projekty jsou free, nicméně licence nebyla zatím vyjasněna. Proto škrtám.

**Comment by yaqwsx** [comment]
Velmi se mi líbí guidelines projektu a postup na rozchození. Za ně máš u mě palec nahoru. Pravidla mi přijdou rozumná a líbilo by se mi je kontrolovat automaticky Travisem.

Problémem s licencí máš na mysli to, že jsme projektu TMOU Webu (zatím) nepřiřkli licenci? Měl bys něco proti MIT? Nevidím důvod dávat něco restriktivnějšího.

**Comment by repli2dev** [comment]
Ad licence: má to dva rozměry:
1. Licence samostného kódu v repozitáři, proti MIT nic nemám. Nicméně tohle je hlavně na shodě TMOU týmu, který to financuje, tak musí být s důsledky toho rozhodnutí srozuměn. (Jako nemyslím si, že by ten systém jen tak rychle někdo vzal a postavil na tom jinou šifrovačku či byznys, to prostě není úplně reálné)
2. Travis na GitHub Marketplace musí přidat organizace, což já udělat nemůžu.
