### ISSUE TITLE
XSS

### ISSUE THREAD

**Issue by miiila** [InstruktoriBrno/tmou-web#103]
Některé části jsou ještě zranitelné na XX - například když vkládám html výsledky, které se získají z externí aplikace, která bere název týmu z SSO cookie.
![Screenshot from 2020-11-07 04-56-23](https://user-images.githubusercontent.com/5753758/98519723-7553b100-2271-11eb-99b0-eba88116dbb1.png)

**Comment by repli2dev** [comment]
@miiila co je zde přesně k opravení? Když se vkládá HTML, tak už tomu nijak moc zabránit nejde, vkládá se to prostě neescapované... Escapování názvů týmů je potřeba IMHO zajistit v externí aplikaci při generování toho HTML.

Obecně mi není jasné jak se tam toto dostalo... Pokud to bereš z `TMOU_SSO_JWT`, jakto že to někdo podvrhl? Tým takového jména jsem v 101 nenašel. A JWT token modifikovaný týmem by neměl projít přes kontrolu podepsání, ne?

**Comment by miiila** [comment]
@repli2dev Jsou tam.
<img width="2545" alt="Screenshot 2020-11-10 at 10 20 13" src="https://user-images.githubusercontent.com/5753758/98654224-540cc680-233e-11eb-9703-7155f31005c1.png">

> Když se vkládá HTML, tak už tomu nijak moc zabránit nejde, vkládá se to prostě neescapované

Nemůžeme escapovat/odstraňovat <script> tag? Jasně, že to nebude obecné řešení, ale o to tolik nejde. Případně by se mohl název escapovat při ukládání do cookie. Zamýšlím se teda teď trochu, jestli a jak se escapuje při ukládání do databáze, když se dostane neošetřený do cookie... a jestli z toho neplyne nějaká SQL injection ;-)

**Comment by repli2dev** [comment]
@miiila ah, špatně jsem očividně hledal.

Script tag nepomůže protože metod jak XSS docílit je prostě moc, například když bys je použil v title, tak se obejdeš zcela bez toho, stačí ukončit atribut a přidat `onload, onclick`...

Metody něco někam escapovat při ukládání či předávání někam je dnes už nepoužívaný způsob, protože ti ničí data a protože není správně... mimojiné i právě s ohledem na ty SQL injectiony, protože jedno escapování se dělalo s ohledem na HTML a další s ohledem na SQL, další s ohledem na reguláry...Správně je s daty, která jsou typu data, zacházet při veškerém zobrazování jako daty a ne jako kódem.

SQL injection by z toho plynout neměla, tam escapování hodnot zajišťuje knihovna při vytváření dotazu.

**Comment by miiila** [comment]
@repli2dev OK, tady k tomu došlo tak, že v aplikaci i.tmou.cz se s tím zachází jako s daty a chyba je jen při tom transferu. Ošetřím to tam a zkusím na to myslet.

**Comment by repli2dev** [comment]
@miiila Je tu cesta via CSP, tzn. zamezit spouštění cizího kódu z neznámých zdrojů, ale je s tím dost štvaní, ne ve všech browserech to funguje OK a bude to limitovat i pro budoucí ad-hoc věci (linkování obrázků z externích zdrojů, GA...)

Prošel jsem ještě jednu toky uživatelských dat a z hlediska SQL i HTML/JS injection by to mělo být OK, jediné problémy jsem našel v mailech, kde to escapované nebylo. Zařídil jsem to tedy.

Taky jsem doplnil poznámku pod obsah stránky, že na XSS by to mělo být ověřeno, pokud tam někdo chce to HTML vkládat.

**Strávený čas: 1 hodina**
