### ISSUE TITLE
Stripování vedoucích 0 z VS při párování plateb

### ISSUE THREAD

**Issue by honzikom** [InstruktoriBrno/tmou-web#126]
Vypadá to, že některé banky doplňují vyplněný VS nulami zleva, pak selhává automatické párování plateb.

**Comment by repli2dev** [comment]
![312500945_2261498134008266_8873013119475455396_n](https://user-images.githubusercontent.com/475549/199249735-4b97a119-d218-4d9f-b34b-d6b2dd1f427d.png)

+ přidat kontrolu, že prefix akce nezačíná nulami.
