### ISSUE TITLE
Feature request: Přidat fullscreen funkcionalitu pro výsledkovku

### ISSUE THREAD

**Issue by yaqwsx** [InstruktoriBrno/tmou-web#128]
Výsledková listina je zpravidla široká tabulka, která by se lépe četla na full-screenu - viz:
![Screenshot from 2022-11-06 09-36-05](https://user-images.githubusercontent.com/1590880/200161615-f4f8ff8e-e312-4181-a0f7-f019126257e2.png)
![Screenshot from 2022-11-06 09-35-48](https://user-images.githubusercontent.com/1590880/200161616-a9625127-2213-4c61-af99-3563eff7fd68.png)

Nestálo by za to přidat na výsledkovku tlačítko, které přepne na full-screen (a tlačítko, které přepne zpět)? Stačil by i jeden malý "hackovitý" kousek JS, který:
- odebere třídu `container` top-level kontejneru nebo přenastaví šířku na `w-full`
- nastaví menu na `hidden`
- a šířku obsahu nastaví na `w-full`

(přesně tak byl získán screenshot v úvodu).

**Comment by repli2dev** [comment]
Může být, tuším už se to někdy diskutovalo, jen ve variantě: stránky budou mít fullscreen příznak (a menu by to neskrývalo)

**Comment by repli2dev** [comment]
Realizováno ve variantě pro všechny stránky -- toggle pod obsahem s ikonkou, volba skryje menu a patičku, je to zapamatované v prohlížeči, takže obnovování výsledků nebude pain ;-)
