### ISSUE TITLE
Správa multimédií

### ISSUE THREAD

**Issue by repli2dev** [InstruktoriBrno/tmou-web#13]
Vybrat nějaký jednoduchý způsob pro správu multimédií (obrázků, videí, PDF...), který bude otevíratelný ze správy statických stránek #3 při čemž vloží absolutní cestu vzhledem k / zpátky do editoru.

Strávený čas:
1.5 hodiny (25. října 2019)
10 hodin (28. října 2019)

**Comment by repli2dev** [comment]
Vypadá to, že tohle budeme muset naimplementovat po svém, sice toho po internetu válí spousty, ale konstrukčně dodávají slepenec PHP a JS, prakticky žádný není udržovaný a riziko XSS a jiných zranitelností je vcelku velké :-/

**Comment by repli2dev** [comment]
Bude nutné také myslet na to, že je potřeba řešit oprávnění, aby se náhodou nedalo k souborům přistoupit přímo když někdo bude znát adresu.

**Comment by klusidy** [comment]
Obrázky a pdfka chceme, nejpozději při odhalení řešení šifer.

**Comment by repli2dev** [comment]
Rozvážil jsem to a můj návrh je následující:
- V přidání/editaci stránek přidat tlačítko, které otevře file manažer.
- Bude public složka `storage` (tzn. napřímo dostupná z prohlížeče).
- V rámci filemanažeru půjde spravovat obsah ve složce `storage`: upload, vytváření složky, přesun souborů, přejmenování souborů, zobrazení náhledu.
- Z filemanažeru bude vybratelný soubor, který po potvrzení vloží jako link/obrázek ve formátu Texy - dle výběru.

Kontrola oprávnění je na jednotlivých souborech je overkill, protože by byla na stránkách, blocích a samotných souborech -- zbytečně chybová záležitost to pak celé nastavit správně... Zabránění předčasného přístupu se zajistí vhodným a neodhadnutelným pojmenováním souborů/složek... Jestli se nepletu dělal to tak i starý web.

(Minimalistické zadání kdyby se neměl stihnout celý rozsah: upload a výběr souborů do editoru)

**Comment by repli2dev** [comment]
Je to provedeno, je to přibližně střední rozsah, což znamená že všechno jde: nahrávat soubory, přejmenovávat soubory, mazat soubory, vytvářet adresáře, mazat adresáře, přesouvat soubory.

Ne všechno je ale uživatelsky přívětivé (žádný drag & drop, přejmenování adresářů chybí)... pro potřeby webu by to mělo stačit a když tak se to dá dodělat později, jen je to časově už hodně náročné.

Co se týče vkládání dal jsem tam tagy pro vložení:
- obrázku
- obrázkového odkazu
- odkazu s názvem souboru
- odkazu s volitelným textem

Případné dokonfigurace (velikosti, alt texty, zarovnání...) je potřeba dodělat ručně v Texy, tam už je prostor kombinací příliš velký na současné zadání.

A ještě jedna zrada oproti Dokuwiki, není tu nic co by generovalo správně velké náhledové/zmenšené obrázky, takže když tam vložíte obrázek o 1000px, bude tam. Pokud chcete menší je nutné si ho vytvořit a nahrát.
