### ISSUE TITLE
Správa menu

### ISSUE THREAD

**Issue by repli2dev** [InstruktoriBrno/tmou-web#16]
Nová agenda ve které se budou spravovat menu. Spravují se konkrétně položky menu, které mají následující atributy:

- Ročník (ve kterém se mají zobrazovat) - může být i prázdné pro stránky, které jsou bez ročníku. (TBD toto vypadá nedomyšleně)
- Stránka v ročníku / Stránka bez ročníku
- Označení skupiny - klíč podle kterého se to seskupí a seřadí (nikde se nebude zobrazovat).
- Váha v rámci skupiny
- CSS třída
- Text
- Datum a čas odhalení
- Stav týmu při kterém se má položka odhalit.
- Pro přihlášené / Pro přihlášené ve správném ročníku

Strávený čas:
30 m (2019-10-11)
5 hodin (2019-10-18)
4 hodiny (2019-10-25)

**Comment by repli2dev** [comment]
Největší otázkou je jestli to není overkill, který se bude horko těžko zpracovat a nebude lepší vymyslet menu, které bude víceméně pro všechny ročníky stejné, jednotlivé položky se budou odhalovat podle času... a v některých místech bude blok pro přidání vlastních stránek.

Spolu s tímhle je potřeba vymyslet i jak zacházet se stránkami bez ročníku -- nemít je náhodou ve všech ročnících jako poslední blok?

**Comment by yaqwsx** [comment]
Původní návrh se mi líbí - tj. každý ročník má své menu, které je seznam položek, resp. seznam položek ve skupinách. Když vytvořím ročník, je předvyplněno výchozí menu. Přijde mi to jako univerzální a přesto dostatečně jednoduché.

Každá položka v menu obsahuje:
- text
- css třídu
- typ: odkaz na stránku v ročníku x, obecné URL, speciální (přihlášení apod)
- datam/čas odhalení
- pro přihlášené
