### ISSUE TITLE
Předvyplněná databáze pro lokální vývoj

### ISSUE THREAD

**Issue by yaqwsx** [InstruktoriBrno/tmou-web#18]
Do budoucna by bylo vhodné mít v lokálním deploy předvyplněnou databázi tak, aby se potenciálnímu vývojáři otevřel web, který má jeden běžící ročník s běžící registrací a zaregistrovaným jedním týmem. Usnadní to lokální vývoj pro vývojáře s webem dobře neseznámeným.

**Comment by klusidy** [comment]
pro mě nízká priorita, nebudu to rozbíhat lokálně

**Comment by repli2dev** [comment]
@klusidy je to otázka půl hodiny, který bude šetři čas opakovaně.

Strávený čas:
1 hodina (8. listopadu 2019)

**Comment by klusidy** [comment]
Ok, to je slušný ROI :-)

**Comment by yaqwsx** [comment]
@klusidy jde o to, že až za rok budeš chtít udělat drobnou změnu na webu, tak ji nechceš dělat na živém kódu jako se to dělalo do teď. A v ten moment ztratíš minimálně 30 minut tím, abys to celé rozběhl.

**Comment by repli2dev** [comment]
Nakonec mi to zabralo trochu víc, ale stále myslím, že se to dost vyplatí :-)
