### ISSUE TITLE
Uživatelé

### ISSUE THREAD

**Issue by repli2dev** [InstruktoriBrno/tmou-web#2]
Přidat kompletní podporu pro uživatele (!= týmy), kteří budou mít možnost se přihlásit/odhlásit/změnit svůj profil a budou spravováni uživateli s dostatečnými právy.

Role uživatelů:
- ORG

Na tuto roli se bude mapovat skupina z Keycloaku, větší granularita (vícero mapování) je možné a právě z důvodu rozšiřitelnosti jsou ty role uživatelů už zde řešeny. Obecně ale předpokládám, že TMOU orgové jsou rovnostářští (jako dosud) a jen používají dělení rolí v týmu, které typicky jednotlivci respektují a naopak spíš občas využívají té flexibility, že někdo někdy za někoho po domluvě zaskočí (bez zbytečné byrokracie).

Uživatel má následující atributy:
- Jméno
- Příjmení
- E-mail
- Identifikátor z Keycloaku
- Role
- Datum a čas posledního přihlášení

Správa se bude řešit v Keycloaku, při každém přihlášení se bude ověřovat jestli má ještě uživatel oprávnění ke TMOU (a v jaké roli), zároveň se též aktualizují jeho údaje, pokud se změnili.

Žádné správcovské funkce, kromě obyčejné tabulky zobrazující uživatele, kteří se přihlásili.

Uživatelé se mohou:
- Přihlásit
- Odhlásit

Strávený čas:
- 30m (4. dubna 2019)
- 7h (19. dubna 2019)
- 2h (24. dubna 2019)
- 2h (26. dubna 2019)

**Comment by spacekpe** [comment]
Poznámky na okraj:
- Pokud se půjde přihlásit pomocí OpenID nebo jiného standardního protokolu, tak uživatelé budou moct používat SSO na login.instruktori.cz - odpadá nutnost pamatovat si extra heslo.
- IS používá pro SSO systém Keycloak, takže nabízím možnost použít na správu uživatelů ten. Uživatelé by se pak spravovali v Keycloaku a aplikace by dostávala informaci o tom, že uživatel X je přihlášen a je členem skupin Y,Z. Možná by se tak dalo vyhnout vývoji UI pro správu uživatelů.

Kdyžtak se ptej!

**Comment by repli2dev** [comment]
@spacekpe Ta možnost tu je, nicméně si to musí říct @yaqwsx...

V obecnosti jde o to zodpovědět dle mého následující otázky:
 - Lze delegovat správu údajů na TMOU správce?
 - Lze přidávat do systému transparentně externisty (TMOU jich mývá hodně.)
 - Lze přidávat lidi dopředně? (Tzn. před prvním přihlášením?)

**Comment by spacekpe** [comment]
3x ano :-)

**Comment by yaqwsx** [comment]
Provázanost s jednotným přihlašování Instruktorům je za mě jednoznačné plus!

@spacekpe: Jak je to se správou Keycloaku? Je možné přidělit např. garantovi ročníku právo přidávat uživatele a přidávat je do skupin s prefixem `tmou-`? Nebo by bylo kvůli každému přidání uživatele/změně nutné psát na Citron?

**Comment by repli2dev** [comment]
@yaqwsx pokud nebude potřeba dělat správ per ročnících/agendách, tak bude stačit vlastně jen jedna skupina.

**Comment by repli2dev** [comment]
@spacekpe ještě je otázkou to případně s Keycloakem vyvíjet na lokále... Máme nějakou testovací instanci? Dá se to rychle rozběhat na lokále (ideálně by se hodil odkaz na nějaký tutorial/dokumentaci).

**Comment by repli2dev** [comment]
@spacekpe odpovím si sám.. Reálně to znamená přejít s lokálním nasazením na docker-compose, kde keycloak bude nasaven.

**Comment by spacekpe** [comment]
Ahoj.

Můžeme ti klidně přidat aplikaci do produkčního Keycloaku, to ničemu nevadí. Může to být ale libovolný z podporovaných standardních protokolů, tj. lze použít i jinou implementaci. Nicméně když bys chtěl pomoct s rozchozením Keycloaku lokálně tak řekni, už s tím máme zkušenosti.

**Comment by repli2dev** [comment]
@spacekpe zatím dobré v kontejneru to zatím vypadá velmi jednoduše.

**Comment by repli2dev** [comment]
Přihlašování víceméně funguje, vyžádalo si to poměrně dost konfigurace Keycloaku a ještě s ním nejsem úplně hotov (problém s self-signed certifikáty).  Pak už bude zbývat akorát přehledový grid uživatelů.

**Comment by repli2dev** [comment]
Už chybí jen dokončit grid s přehledem uživatelů.

**Comment by repli2dev** [comment]
Je to hotové, čeká to ale na zamergování #10.

**Comment by repli2dev** [comment]
#10 bylo zamergováno, a v #12 to je tedy připraveno k CR.
