### ISSUE TITLE
Párování plateb z transparentního účtu

### ISSUE THREAD

**Issue by repli2dev** [InstruktoriBrno/tmou-web#20]
1. Automatický CRON, který se při spuštění podívá na transparentní účet, vezme platby se správným prefixem pro otevřené ročníky a zkusí je správat s týmy. V případě shody musí být částka alespoň taková, jaká je v nastavení pro daný ročník.

2. Ruční změna stavu zaplacení u jednoho týmu v administraci.

3. Zobrazení párovacího logu -- bod 1 bude o své činnosti dávat informace do logu, který půjde zobrazit pro případné dohledávky.

Strávený čas:
- 2h (2019-10-04)
- 3h (2019-10-11)

**Comment by klusidy** [comment]
Minulý web uměl vypsat platby které měly správný VS, ale špatnou částku (to se dělo u slovenských týmů) anebo špatný VS a špatnou částku (protože lidi neumí ctrl C, ctrl V), celkem se to hodilo.
