### ISSUE TITLE
Hromadná změna stavu týmů

### ISSUE THREAD

**Issue by repli2dev** [InstruktoriBrno/tmou-web#21]
Import, který dostane import <číslo týmu>/<název týmu>;nový stav.

Tento stav týmu nastavím, finálně vytiskne statistiku kolik jakých týmu změnil (nových stavů).

Strávený čas:
2 hodiny (3. 10. 2019)

**Comment by klusidy** [comment]
Jaký je usecase? Mě napadají tyto změny stavu týmů:
 1) po konci kvalifikace (nastavení 220 týmů na kvalifikované)
 2) po divokých kartách (jde naklikat ryčně)
 3) po zaplacení (viz issue párování plateb z transparentního účtu)
 4) po odhlášení (viz issue oslovování náhradníků)

Use-case tohoto issue vidím jen v prvním případě. Na minulém webu se po kvalifikaci spouštěl skript, který to poměnil v databázi.

Co ale šlo na minulém webu bylo filtrování a vybírání týmů a následná změna stavu těmto vybraným týmům (s tím se řešily use-casy 2-4)

**Comment by repli2dev** [comment]
Hotové, individuální až hromadné změny se dají řešit na seznamu týmů. 

Dávkové pak na samostatné stránce.

Změny po zaplacení se budou dělat v rámci samostatného tasku.
