### ISSUE TITLE
Úplný/částečný export dat o týmech

### ISSUE THREAD

**Issue by repli2dev** [InstruktoriBrno/tmou-web#22]
Výstupem bude CSV s kompletními údaji o týmu včetně členů - v případně částečného pak jen základní info Jméno, číslo týmu, tajná fráze, e-mail, telefon.

Strávený čas:
- 1h 30m (23. 9. 2019)

**Comment by klusidy** [comment]
Toto je potřeba mít po ruce na hře. Vytištěné, tedy vyexportované.

**Comment by yaqwsx** [comment]
A po zkušenosti z loňska se to hodí na hře i když je potřeba skriptem filtrovat týmy (případ, kdy jsme při výpadku webinfa hledali týmy, které splňovaly nějaké vlastnosti a chtěli jsme jejich telefonní čísla).
