### ISSUE TITLE
Týmové review hry

### ISSUE THREAD

**Issue by repli2dev** [InstruktoriBrno/tmou-web#23]
Možnost po hře nastavit link na reportáž a vyplnit co se líbilo, co se nelíbilo a první dojmy.

Zobrazit v menu (po hře) a zobrazení obsahu od všech týmů.

Strávený čas:
1.5 hodiny (25. října 2019)

**Comment by klusidy** [comment]
Pokud to po hře nebude, přijdeme o často jedinou zpětnou vazbu od některých týmů a to by byla škoda. Ideálně to mít na webu v autentizované sekci hned po přihlášení.

**Comment by repli2dev** [comment]
Navrhuji následující:
- je-li po hře, zobrazí se hned na úvodní stránce box s žádostí o vyplnění textu (zmizí buď po vyplnění, nebo po 14 dnech).
- Uživatel může vyplnit a kolikrát chce změnit: co se líbilo, co se nelíbilo, ostatní, link na reportáž.
- Bude jedna stránka na které se zobrazí pod jednotlivými nadpisy příslušné položky od všech týmu, co to vyplnili.
