### ISSUE TITLE
Kopie ročníku

### ISSUE THREAD

**Issue by repli2dev** [InstruktoriBrno/tmou-web#24]
Strávený čas:
1 hodina (9. listopadu 2019)

**Comment by klusidy** [comment]
Toto se na minulém webu dělalo ručně, takže tímto se to jenom zlepší. Ale priorita je zatím nízká (stačí kdykoli během jara...)

**Comment by yaqwsx** [comment]
V tento moment mě napadá, jestli nedává ještě smysl mít možnost skrýt ročník (dokud není celý nachystaný). Co si o tom myslí @klusidy ?

**Comment by klusidy** [comment]
@yaqwsx Nice to have, ale not must have. Předpokládám, že typicky se nový ročník bude vytvářet během jednoho odpoledne někdy na jaře.

**Comment by repli2dev** [comment]
Návrh je za mě následující:
 - Založení ročníku proběhne ručně
 - Půjde do něj zkopírovat z vybraného ročníku: stránky & položky menu - kopírovat se bude tak jak jsou, u položek menu dojde k automatické přepnutí ročníku... (V rámci stránek se to bude muset provést ručně, stejně jako nastavení odhalování atp.)

Skrývání ročníku bych nedělal, je to hodně práce (to jestli je skrytý by se muselo ověřovat na hodně místech) a vůči tomu přínosu to dle mého nestojí za to.

Může být?
