### ISSUE TITLE
Hromadné mailování týmům

### ISSUE THREAD

**Issue by repli2dev** [InstruktoriBrno/tmou-web#25]
Jde odeslat e-mail týmům, které jsou v určitém konkrétním (jednom či více stavech).  Jde zadat předmět i text, je vidět náhled.

Strávený čas:
2.5 hodiny (1. 10. 2019)
0.5 hodiny (2. 10. 2019)

**Comment by klusidy** [comment]
Chci umět týmy filtrovat podle stavů a odeslat jim email.
Chci umět vybrat tým(y) manuálně a odeslat jim email.

**Comment by klusidy** [comment]
Chci v mailu umět používat hromadnou korespondenci stylem: "Milý týme @TYM@, " (nebo tak nějak), aby se to každému týmu nahradilo jeho vlastními údaji.

**Comment by klusidy** [comment]
Budeme umět poslat mail všem historickým účastníkům? (je to nejlepší propagační kanál, co TMOU má)

**Comment by repli2dev** [comment]
@klusidy souhlas, mělo by to fungovat stejně jako u stránek, kde už jsou tyto makra implementovány.

**Comment by repli2dev** [comment]
Bylo včera zamergováno.
