### ISSUE TITLE
Fórum

### ISSUE THREAD

**Issue by repli2dev** [InstruktoriBrno/tmou-web#26]
Strávený čas:
45 minut (29. 10. 2019)
30 minut (31. 10. 2019)
10 hodin (1.-3. listopadu 2019)

**Comment by klusidy** [comment]
Líbilo by se mi mít fórum s vklákny. A ještě víc, kdyby po hře měla každá šifra vlastní vlákno dostupné ze stránky šifry.

**Comment by repli2dev** [comment]
Řada otázek:
 - Diskuze pod (některýma stránkama) vs. samostatná stránka Fórum?
 - Mohou týmy vytvářet vlastní vlákna? Jsou/mohou být vlákna navázané na stránky (Šifra XY, Pravidla)
 - Mají být vlákna vázaná na ročník? Respektive má fórum být mimo ročníky, nebo v každém ročníku zvlášť?
 - Má být v rámci jednoho vlákna více úrovní zanoření, nebo jen jedna (jako to bylo dříve).
 - Co chceme povolit za formátování? (B, i, citaci, link, seznamy)

**Comment by miiila** [comment]
> Diskuze pod (některýma stránkama) vs. samostatná stránka Fórum?

Samostatná stránka.

> Mohou týmy vytvářet vlastní vlákna? Jsou/mohou být vlákna navázané na stránky (Šifra XY, Pravidla)

Mohou, pouze přihlášené. Fórum je samostatné, na nic navazovat nemusí. Základní vlákna vytvoříme sami.

> Mají být vlákna vázaná na ročník? Respektive má fórum být mimo ročníky, nebo v každém ročníku zvlášť?

Nejsm si úplně jistý, líbilo by se mi něco ve smyslu starého fóra (https://archiv.tmou.cz/talk/conversations/tmou-19.html), což chápu tak, že mám top vlákno s ročníkem a v něm tematická vlákna + pár dalších (Obecné, Technické problémy).

> Má být v rámci jednoho vlákna více úrovní zanoření, nebo jen jedna (jako to bylo dříve).

Ne, resp. jsem pro top vlákna a v nich tematická vlákna, jak jsem se snažil naznačit výše. Vychází mi z toho dvě úrovně zanoření.

> Co chceme povolit za formátování? (B, i, citaci, link, seznamy)

Klidně všechno to, co jsi napsal, asi nic navíc (pozor na XSS). Pokud to je implementačně složitejší, tak klidně nic, jen plain text.

----

Obecně tady potřebujeme spíš být rychlí a iterovat po menších kusech. Takže se snažme nezavřít si cestu, ale pokud nebude na začátku implementováno vlákno per ročník, tak je to jedno. Zároveň je hodně potřeba dávat pozor na spam, příkladem může být opět Interlos a jeho registrace. Dokonce bych klidně zvážil přispívání jen přihlášeným týmům (nevím, jak to bylo na minulém). Prostě pokud nám chce někdo něco říct, mělo by to být adresné.

**Comment by yaqwsx** [comment]
> * Diskuze pod (některýma stránkama) vs. samostatná stránka Fórum?

Mě osobně by líbilo mít fórum jako samostatnou stránku + mít možnost vložit jedno konkrétní téma pod řešení šifry. Vkládání dle mě ale není priorita a klidně mi letos bude stačit i odkaz.

> * Mohou týmy vytvářet vlastní vlákna? Jsou/mohou být vlákna navázané na stránky (Šifra XY, Pravidla)

Pro účely TMOU si dovedu představit i model, kde týmy nemůžou vytvářet vlákna a my máme vlákna k šifrám + obecné.

> * Mají být vlákna vázaná na ročník? Respektive má fórum být mimo ročníky, nebo v každém ročníku zvlášť?

Co ročník, to nové fórum za mě.

> * Má být v rámci jednoho vlákna více úrovní zanoření, nebo jen jedna (jako to bylo dříve).

Osobně mi stačí jedna úroveň, hezké by bylo mít podporu pro anotace, kde #<číslo příspěvku> by vyrobilo klikací odkaz (ať můžu reagovat a je jasné na co). Otázka jestli ale 2 úrovně, které navrhoval Míla nejsou to samé, ale přehlednější.

> * Co chceme povolit za formátování? (B, i, citaci, link, seznamy)

Toto stačí; podle mě ani obrázky netřeba vkládat.

Souhlasím s @miiila, že určitě by mělo být možné přispívat pouze přes přihlášený účet týmu.

**Comment by repli2dev** [comment]
Ok, udělám to jako stránku v rámci ročníku, kde půjde zakládat vlákna týmy i organizátory, v rámci vlákna budou týmy moci týmy i organizátoři dávat příspěvky s B, i, citací a seznamy. Orgové budou moci vlákna mazat, případně jednotlivé příspěvky skrýt.

**Comment by repli2dev** [comment]
Když nad tím přemýšlím znovu tak stránka fóra na ročníku bude nešikovná, protože když pak hledání něčeho co jsem viděl ve fóru může být dost nešikovný proces. Navrhuji tedy udělat sice stránku, která bude přidatelná do ročníku, ale bude vždy ukazovat všechny vlákna.
