### ISSUE TITLE
Komunikace s týmy

### ISSUE THREAD

**Issue by repli2dev** [InstruktoriBrno/tmou-web#27]

**Comment by klusidy** [comment]
Chci umět odesílat mail týmům (viz issue Hromadné mailování týmům) a chci mít fórum (viz issue fórum). Během hry možná vývěsku ve webinfu(?). Další kanál podle mě netřeba

**Comment by repli2dev** [comment]
@klusidy můžeme klidně zavřít, ale v úvodní komunikaci s @yaqwsx padlo, že byste to z mailů chtěli převést do webu, aby byla vidět historie i mezi orgy.

Za mě je to spíš nepreferované, komplikuje to systém, lidem komunikaci a stejně komunikuje spíše méně lidí. (TMOU není komunikačně orientovaná, aby to ospravedlnilo ty náklady).

**Comment by klusidy** [comment]
No a taky lidi víc kontrolujou maily než autenizovanou sekci (tam si toho min 80 % lidí nevšimne).

Na historii mezi orgy by bylo asi jednodušší vyčítat google group tmou@instruktori.cz a dávat odpovědět všem

**Comment by yaqwsx** [comment]
S odstupem času si stále myslím, že je to hezká feature, ale nestojí za vložené úsilí - zejména v momentě, kdy Instruktorům už pěkně fungují Google groups. Za mě ji klidně můžeme vypustit.

**Comment by repli2dev** [comment]
Ok, zavírám.
