### ISSUE TITLE
Poloautomatické nasazování

### ISSUE THREAD

**Issue by repli2dev** [InstruktoriBrno/tmou-web#28]
Stojí to za to? Lze to na instruktorském železe realizovat?

Strávený čas:
1 hodina (2. 10. 2019)

**Comment by klusidy** [comment]
Předpokládám, že nemluvíte o nasazování týmů, takže na to nemám názor.

**Comment by yaqwsx** [comment]
Osobně mám automatický deployment rád.

Určitě bych se chtěl vyvarovat situaci, kdy jediným člověkem schopným nasadit web budeš jenom ty. Za mě jsou možné dvě varianty:
- poloautomatický deploy, kdy se připojím na admirala, spustím skript a on nasadí novou verzi z repozitáře.
- předchozí varianta rozšířená o to, že úspěsný Travis z master větve pingne admirala (s nějakým secretem), že má aktualizovat.

**Comment by repli2dev** [comment]
Za sebe bych hlasoval za poloautomaticky deploy v podobe scriptu, prijde mi to jako nejlepsi pomer k riziku - nasazujes explicitne a ses u toho pritomen, takze je mensi riziko, ze nekdo neco pushne a o x dni pozdeji zjisti nekdo ze cela stranka nefunguje.

**Comment by yaqwsx** [comment]
OK.

**Comment by repli2dev** [comment]
Zrealizováno, mělo by stačit vlézt na server a spustit alias/příkaz `deploy-tmou`.

**Comment by repli2dev** [comment]
Ehm, zapomněl jsem, že tam není sdílený uživatel:

`alias deploy-tmou="read -p 'Press any key to DEPLOY TMOU, cancel with CTRL-C...' && cd /var/www/www.tmou.cz/ && bash deploy.sh production"`

Bez pullu (např. když nejsou práva, nebo je lokální ad-hoc změna)
`alias deploy-tmou="read -p 'Press any key to DEPLOY TMOU, cancel with CTRL-C...' && cd /var/www/www.tmou.cz/ && bash deploy.sh production no-pull"`
