### ISSUE TITLE
"Zobrazit jako" funkce

### ISSUE THREAD

**Issue by klusidy** [InstruktoriBrno/tmou-web#29]
Na debugování a kontrolu se hodí mít možnost zobrazit web tak, jak ho vidí registrovaný/kvalifikovaý/vyřazený tým.

**Comment by klusidy** [comment]
Jako org nyní vůbec nevím, co se zobrazuje týmům po přihlášení a nemám způsob, jak to zjistit, než si založit tým

**Comment by repli2dev** [comment]
Tento task je už hotový, stačí přejít do seznamu týmů a kliknout u příslušného týmu na ikonku uživatele v jeho řádku -- ta do toho uživatele impersonikuje a dívá se na web jeho očima. (Čas jde nastavit separátně.)

**Comment by repli2dev** [comment]
Hmm, možná to bylo myšleno podívat se jako neexistující tým v daném stavu?

**Comment by klusidy** [comment]
Většinou máme dost týmů ve všech stavech (a kdyby ne, tak není problém si nějaký vyrobit). 

Potvrzuji zavření.
