### ISSUE TITLE
Statické stránky

### ISSUE THREAD

**Issue by repli2dev** [InstruktoriBrno/tmou-web#3]
Vyžaduje realizované ročníky, viz #6.

V systému existuje typ stránka, ten má následující parametry:
- Titulek (pro prohlížeč)
- Nadpis (pro uživatele)
- Ročník - volitelné.
- Obsah stránky
- Příznak zda je stránka skrytá (~ nepřístupná všem vyjma organizátorům) - v menu i obsah
- Volitelný časový okamžik kdy stránku odhalit
- Příznak zda je úvodní stránkou ročníku - taková může být jen jedna
- SLUG - řetězec použitý v URL adrese, jednotlivé stránky budou přístupné na adrese `/<id ročníku>/<SLUG>`, úvodní stránka celého webu se přesměruje na úvodní stránku ročníku. Některé SLUGy jsou rezervované, viz níže.

Co se týče odhalování a skrývání, neřešil bych na úrovni celých stránek, ale na úrovni bloků (jako bylo dosud, protože je to výrazně flexibilnější. Reálně bych to naimplementoval jako speciální post-processor pro zobrazovaný text.

Naimplementovat v systému jeden zdroj pro data a času. Pro uživatele (organizátory) bude k dispozici panel, kde budou moc zadat svůj čas, kterým se pak na systém budou dívat.

Co se týče formátování, stačí Texy (něco jako Markdown) rozšířenou o:
- Časem chráněné bloky
- Stavem týmu podmíněné bloky
- Makra pro jméno týmu, číslo týmu, variabilní symbol,
- Makra pro název ročníku, číslo ročníku, motto ročníku.

Vedle editoru půjde otevřít správce multimedií, viz #13. Při vybrání se zpátky přenese adresa (např. `/data/20/sifry/1.pdf`.

Stránky budou spravovatelné v gridu, na který se půjde dostat buď přímo z administračního menu (a potom budou vidět jen stránky bez ročníku) a nebo skrze konkrétní ročník v gridu ročníků, kde pak budou vidět jen stránky daného ročníku. Stránky půjde přidávat, upravovat a mazat. U každé stránky bude také v patičce odkaz na úpravu.

Některé stránky budou udělané automaticky a jejich SLUG bude rezervovaný (víceméně budou vytvořeny automaticky v každém ročníku):
- Seznam registrovaných týmů
- Seznam hrajících týmů
- Seznam kvalifikovaných týmů
- Statistika kvalifikace
- Statistika odpovědní kvalifikace
- Reportáže týmů
- Statistika šifer
- Průchod hrou
- Nastavení týmů

Otevřené otázky:
- Jak to přidávat a řadit do menu? Co se skupinami v menu?

Strávený čas:
- 30m (6. dubna 2019)
- 1h (3. května 2019)
- 1h (29. května 2019)
- 1h (14. června 2019)
- 1h (17. června 2019)
- 1h (19. června 2019)
- 3h (23. června 2019)
- 5h (24. června 2019)

**Comment by klusidy** [comment]
Chci umět automaficky skrývat/zobrazovat stránky v menu podle času (zobrazit odkaz na řešení s koncem hry).

**Comment by klusidy** [comment]
Chci umět vkládat dynamický obsah do stránek/přidávat statický text k dynamickým stránkám (seznam kvalifikovaných + vysvětlivky nebo text s individuálním VS v autentizované sekci)

**Comment by klusidy** [comment]
Markdown/texy je za mě ok

**Comment by klusidy** [comment]
Chci mít možnost stránky odkazující na minulé ročníky (~archiv na minulém webu)

**Comment by klusidy** [comment]
Hodí se umět vytvořit stránku zkopírováním stránky z minulého roku (aai půjde copy-paste), případně i zkopírováním kompletního ročníku (kopírovat ručně stránky pro seznamy týmů býval opruz). Asi low priority tohleto

**Comment by repli2dev** [comment]
@klusidy dynamický obsah ve statických stránkách jsem přidal; volíme Texy.

Co se týče zbytku:
- Odkazování na minulé ročníky -- nevím co tím máš přesně namysli... odkazovat se půjde via HTTP link, nebo absolutní cestu v rámci webu, vyklikatelné tohle úplně není.
- Zkopírování stránek - bych řešil v budoucnu, formuláře a další automatický obsah se bude ale dělat automatizovaně, to už by by moc velký opruz.
- Menu - zatím stále nemám moc nápad jak to řešit jinak, než totální freeform HTML pole, nebo kompletní full-featured agendu, kde člověk bude celé menu uspořádávat.

Další postřehy:
 - Předpokládám, že některé články plně z ročníku vyhodíme, byť tam doteď byli, například O TMOU, atp. že?

**Comment by repli2dev** [comment]
Je to připraveno k CR v PL !15

- Makra pro týmy jsou nafejkované, stejně tak předpokládám, že při realizaci týmů přidám ještě makra pro počet týmů v jednotlivých kategoriích.
- Je tam zárodek hodin pro simulaci času.
- Správce multimédií (a jejich vkládání) se bude řešit v samostatném tasků a klidně i později (pro začátek to může být i spartanské)
- Menu se bude řešit taky samostatně a plně konfigurovatelně, všechny ostatní kompromisy někde drhnou.

**Comment by yaqwsx** [comment]
Za mě OK.
