### ISSUE TITLE
Autentizovaná sekce

### ISSUE THREAD

**Issue by klusidy** [InstruktoriBrno/tmou-web#30]
Jako org nevím, co se zobrazuje týmům v autentizované sekci.

Chci umět měnit co se zobrazuje v autentizované sekci, chci umět zajistit, aby týmy s různými stavy viděli různé věci (typicky po kvalifikaci údaje o placení nebo ne). Minulý web uměl nahradit např. řetězec @VS@ za skutečný variabilní symbol týmu, který byl přávě přihlášený

**Comment by repli2dev** [comment]
@klusidy nevím co myslíš autentizovanou sekcí, nic takové podle mě neexistuje -- když je tým přihlášen, jen přesměrován na úvodní stránku...

Stránky ale už mají bloky (viz nápověda k formátování pod editačním formulářem) pro skrývání dle stavu, času, makra pro týmy atp.

Takže za mě je tento task k zavření.

**Comment by klusidy** [comment]
Aha, aha, no koukám, že je toho víc, než jsem tušil. 
Fajn, info o placení a poslední informace můžeme dát na úvodní stránku do těchto bloků.

Closing.
