### ISSUE TITLE
Skrývací toggle

### ISSUE THREAD

**Issue by klusidy** [InstruktoriBrno/tmou-web#31]
Řešení šifer je mít pohodlné na stejné stránce jako zadání (aby se nemuselo překlikávat do jiného tabu), ale současně to nechceme ukazovat hned viditelně (aby si to lidi mohli projít a na řešení se podívat jen, pokud chtějí).

Řešením je podle mě přidat do markdownu něco, co způsobí, že odstavec bude skrytý, dokud si ho uživatel nezobrazí.

**Comment by repli2dev** [comment]
Dobrý nápad.

P.S. Nemáme markdown ale texy, právě kvůli rozšiřitelnosti. Syntax se liší.

Odpracované:
1h 30m (20. 9. 2019)
