### ISSUE TITLE
Časové skrývání obsahu na stránce

### ISSUE THREAD

**Issue by klusidy** [InstruktoriBrno/tmou-web#32]
Starý web uměl skrýt/zobrazit podle času i obsah stránky, nejen celou stránku. Řešili jsme s tím zobrazování položek v menu (menu byla samostatná wiki stránka) a občas se to hodilo i pro obsah (když s

**Comment by yaqwsx** [comment]
To už současný systém umí - proto je dole v patičce zobrazený čas a v admin menu máš možnost nastavovat virtuální čas, aby otestoval změny.

**Comment by repli2dev** [comment]
Je to jak praví @yaqwsx. S dovolením zavírám
