### ISSUE TITLE
Fixnout mobilní prohlížeče

### ISSUE THREAD

**Issue by repli2dev** [InstruktoriBrno/tmou-web#37]
Na Androdiu ve FF nejde kliknout a zobrazit menu.

Na iOS ve FF a Safari nejde skrolovat rychleji (vždy se to zastaví) a menu se restartuje při scrolu.

Strávený čas:
- 6 hodin (4. 10. 2019) - veškeré ladění stylů a designu

**Comment by repli2dev** [comment]
na iOS už můžu scrollovat, má to ale artefakty po čase skrolování nahoru a dolů, což asi nezbyde než abych se na to podíval já. A taky menu lišta občas mizí...

Na Androidu prosím vyzkoušet.

**Comment by yaqwsx** [comment]
Na Androidu 7 aktuální Chrome a Firefox fungují. Pokud se na to na iOS podíváš, budu rád - nemám to jak otestovat.

**Comment by yaqwsx** [comment]
PS: Je možné, že na iOS je problém s tím, co scrollovat - jestli hlavní stránku nebo menu.

**Comment by repli2dev** [comment]
@yaqwsx je a očividně jsou tam i další bugy, nejlepší bude paralax na iOS vypnout.

**Comment by repli2dev** [comment]
Na iOS a Safari je vypnutý parallax. Na ostatní funguje. Dost jsem potunil jeho rozměry a přesné provedení aby vypadal v různých viewportech co nejlíp. Zároveň jsem opravil menu tak aby pozadím stránky nešlo vůbec scrolovat (dělá to tak bootstrap) když je menu otevřené. Také jsem opravil pár dalších věcí responsivity a zařídil aby se vynutilo stační nového stylu a některých JS když je změníme (resp. když je na serveru nový DI kontejner, což +- stačí).
