### ISSUE TITLE
Zajistit možnost scrolování stránky pomocí klávesnice hned po načtení

### ISSUE THREAD

**Issue by repli2dev** [InstruktoriBrno/tmou-web#39]

**Comment by yaqwsx** [comment]
Momentálně je mi záhadou, co to způsobuje - ani jsem se s tímto problémem nesetkal. Chvíli jsem bádal ale ani to nevypadá na problém s focusem - když ho nastavím z JS, tak se nic nezmění.

Nevíš, čím by to mohlo být? Nebo tip na co se podívat?

**Comment by repli2dev** [comment]
Presne moje zjisteni :/

3. 10. 2019 v 22:08, Jan Mrázek <notifications@github.com>:

**Comment by repli2dev** [comment]
Když změním `<div class="parallax">` na `<div>` tak to najednou začne fungovat správně.

**Comment by repli2dev** [comment]
... a taky začne fungovat swipe scroll na iOS.

**Comment by repli2dev** [comment]
Problémem byla možnost `perspective`, která způsobovala, že prohlížeč nevěděl v čem má scrollovat... manuální focus nakonec funguje, pokud se vyvolává na něčem co má `tabindex`, ale proč, nemám absolutní ponětí...
