### ISSUE TITLE
Týmy

### ISSUE THREAD

**Issue by repli2dev** [InstruktoriBrno/tmou-web#4]
Checkbox, zda-li chtějí dostávat informace o dalších akcích Instruktorů (přihláška do externího adresáře?)

**Comment by repli2dev** [comment]
Ročník (přidat):
- Prefix variabilního kódu

Tým:
- Ročník (chceme mít týmy po ročnících, ať zbytečně nesuplujeme Šifrovačky, nemusíme řešit klany...)
- Číslo týmu unikátní v rámci ročníku
- Název týmu
- Registrační e-mail
- Přihlašovací heslo
- Tajná fráze
- Mobilní telefon (1x)
- Stav týmu - viz níže
- Stav platby - viz níže
- Čas registrace
- Čas poslední změny týmu
- Čas posledního přihlášení
- Čas spárování platby
- Token pro reset hesla
- Čas vypršení tokenu pro reset hesla

Člen týmu:
- Celé jméno
- E-mailová adresa
- Souhlas se zařazením do newsletteru Instruktorů

**Přihlašování: id vs jméno vs e-mail?
Herní indexy a věk - jsou ještě potřeba?**

Stavy týmů:
- registrován - výchozí
- kvalifikován - po úspěšné kvalifikaci či divoké kartě
- nekvalifikován - po neúspěšné kvalifikaci, či diskvalifikaci
- hrající - týmy, které zaplatili.

Stav platby (může být `null` = není relevantní):
- nezaplaceno
- zaplaceno

Stránky & funkce:
- Stránka s registračním formulářem
- Stránka soukromého profilu týmu (změna údajů)
- Stránka s přihlášením
- Odhlášení
- Stránka se seznamem registrovaných týmů
- Stránka se seznamem hrajících týmů
- Stránka se seznamem kvalifikovaných týmů
- Datagrid všech týmů v rámci ročníku (administrační)
- Exportní funkce dat o týmech v CSV (administrační)
- Import stavu týmů z CSV (id týmů/název týmu - stav)
- Import stavu platby z CSV (FIO banky - párování dle variabilního symbolu).


Nutné dořešit (specifikovat jak má být realizováno):
- Statistika kvalifikace
- Statistika odpovědní kvalifikace
- Reportáže týmů
- Statistika šifer
- Průchod hrou

Strávený čas:
- 1 hodina (25. 8.)
- 1 hodina (27. 8.)
- 3 hodiny (30. 8.)
- 8 hodin (31. 8.)
- 1 hodina (1. 9.)
- 1.5 hodiny (2. 9.)
- 4 hodiny (4. 9.)

**Comment by miiila** [comment]
> Přihlašování: id vs jméno vs e-mail?

Nemůžeme mít ještě navíc login? Který si týmy klidně vyberou sami, uniq constraint. Pokud ne, tak asi název týmu, ale je třeba zohlednit například můj oblíbený `¯\_(ツ)_/¯` (ano, opravdu to používám jako název týmu).

> Herní indexy a věk - jsou ještě potřeba?

HI umíme ze šifrovačky.cz, věk bych pro zajímavost nepovinně nechal

> Statistika kvalifikace, Statistika odpovědní kvalifikace, Statistika šifer, Průchod hrou

Data by mělo mít naše webinfo, které vzniká, tedy "jen" zobrazit dodaná data (s @yaqwsx jsme se bavili o tom, že by webinfo vracelo html snippety).

> Reportáže týmů

Asi nerozumím otázce - realizoval bych jako seznam odkazů na reportáže, většina jich teď vzniká na Google docs.

**Comment by repli2dev** [comment]
> > Přihlašování: id vs jméno vs e-mail?
> 
> Nemůžeme mít ještě navíc login? Který si týmy klidně vyberou sami, uniq constraint. Pokud ne, tak asi název týmu, ale je třeba zohlednit například můj oblíbený `¯\_(ツ)_/¯` (ano, opravdu to používám jako název týmu).

Loginy se zapomínaj, proto je dobré vybrat nějaký, na který si člověk skoro vždy vzpomene, typicky e-mail. Ten má ještě výhodu, že není otevřený k zjištění pro zkoušení hesla.

Jméno týmu používá InterLoS, s unicodem není problém, akorát fancy týmy mají problém s rychlým zadáním.
> 
> > Herní indexy a věk - jsou ještě potřeba?
> 
> HI umíme ze šifrovačky.cz, věk bych pro zajímavost nepovinně nechal

ACK.
> 
> > Statistika kvalifikace, Statistika odpovědní kvalifikace, Statistika šifer, Průchod hrou
> 
> Data by mělo mít naše webinfo, které vzniká, tedy "jen" zobrazit dodaná data (s @yaqwsx jsme se bavili o tom, že by webinfo vracelo html snippety).

Bude potřeba vyjasnit.
> 
> > Reportáže týmů
> 
> Asi nerozumím otázce - realizoval bych jako seznam odkazů na reportáže, většina jich teď vzniká na Google docs.

Za mě jsou odkazy OK, starý web měl texty k ročníku a texty k šifrám.

**Comment by miiila** [comment]
> Loginy se zapomínaj, proto je dobré vybrat nějaký, na který si člověk skoro vždy vzpomene, typicky e-mail. Ten má ještě výhodu, že není otevřený k zjištění pro zkoušení hesla.

Email má nevýhodu, že obvykle není týmový, tedy si musím pamatovat, že pro web TMOU používám Cicvárkův mail, pro Bednu Darwina apod. Tedy hlasuji pro jméno týmu, pokud unicode funguje.

> Bude potřeba vyjasnit.

Jo a ideálně co nejdřív :-)

> Za mě jsou odkazy OK, starý web měl texty k ročníku a texty k šifrám.

Asi tomu úplně nerozumím a možná je tam nějaké zmatení. Texty k šifrám, pokud vím, byly pouze ve fóru. Matně si pamatuji nějaké hodnocení obtížnosti a nápadu, ale nikde to nevidím zobrazené a asi to nikdo nijak nevyhodnocuje, takže bych to zrušil. Texty `Co se líbilo`, `Co se nelíbilo` a `Další dojmy a postřehy` bych zachoval.

**Comment by repli2dev** [comment]
@miiila máš pravdu, nechme tedy odkaz na reportáž, free form text "Co se líbilo", "Co se nelíbilo", "Další dojmy a postřehy". Ostatní bych (minimálně zatím) nedělal.

**Comment by yaqwsx** [comment]
> > Statistika kvalifikace, Statistika odpovědní kvalifikace, Statistika šifer, Průchod hrou
> 
> Data by mělo mít naše webinfo, které vzniká, tedy "jen" zobrazit dodaná data (s @yaqwsx jsme se bavili o tom, že by webinfo vracelo html snippety).

Nedochází zde ke zmatení? Webinfo jako takové bude běžet jako samostatná služba, která bude vracet HTML snippet svého výstupu zobrazovaného buď na samostatné stránce (jako to je v případě KučaInfa) anebo vložené do TMOU webu.

Myslím, že @repli2dev se ale ptal na formát, v jakém se budou dostávat výsledky např. kvalifikace nebo hry, aby je bylo možné zobrazit. Je to tak?

**Comment by repli2dev** [comment]
@yaqwsx propojení těchto agend pro výsledky kvalifikace zatím neřeším, na to bude ještě času dost.

**Comment by repli2dev** [comment]
Poznámky:
- Přišel jsem na to, že jsme zanedbávali správné nastavení kódování v DB, ve všech migracích jsem to opravil, při testování bude potřeba smazat databázi a začít znovu.
- Impersonifikace funguje z organizátorů na týmy (a zpět), není tam ale žádné omezení, organizátoři tak můžou vše co týmy (a bude to vypadat, jako by to udělal jejich tým).
- Nedodělky budu odlifrovávat do samostatných úkolů, ať na ně potom nezapomeneme.
