### ISSUE TITLE
Filtrování v mailovacím formuláři

### ISSUE THREAD

**Issue by klusidy** [InstruktoriBrno/tmou-web#49]
Nerozumím, jak funguje vybírání týmů v mailovátku. Čekal bych, že když vyberu stav, zobrazí se mi v seznamu týmů jen týmy s odpovídajícím stavem. Potom v seznamu týmů můžu z takového podseznamu vybrat/vyloučit týmy, které potřebuji.

Pokud jednou vyberu nějaký stav, nejde to "odvybrat".

**Comment by repli2dev** [comment]
Funguje to jako vyber celeho stavu sjednoceno s rucne vybranymi tymy, to ze by to filtrovalo by asi slo taky, ale je slozitejsi udelat.

**Comment by repli2dev** [comment]
Funguje to po úpravách tak, že můžeš vybrat 0-n stavů týmů kterým se má něco poslat... Nebo (tzn. sjednocuje výsledky obou vybraných polí) můžeš vybrat týmy ze seznamu vyfiltrovaných týmů (by default jsou tam všechny) -- filtrovat lze podle stavu týmu tak podle stavu platby.

Task tedy považuji za implementovaný, pokud bys to chtěl nějak jinak, řekni si.
