### ISSUE TITLE
Nefungují mi tmou makra/impersonifikace

### ISSUE THREAD

**Issue by klusidy** [InstruktoriBrno/tmou-web#50]
Vytvořil jsem stránku s makrem TMOU:team_name:
Po impersonifikaci jako náhodný tým je na jejím místě prázdný řetězec. 
Neumím posoudit, jestli je to chyba v makrech anebo v impersonifikaci.

**Comment by repli2dev** [comment]
@klusidy  můžu to zavřít? Příčinu jsme IMHO našli.

**Comment by repli2dev** [comment]
Zavírám, případně založte nový task, pokud problém někde přetrvává.
