### ISSUE TITLE
Nefungují reveal to makra/impersonifikace

### ISSUE THREAD

**Issue by klusidy** [InstruktoriBrno/tmou-web#51]
Vytvořil jsem stránku s makrem /---reveal to qualified teams
Po impersonifikaci kvalifikovaného týmu nevidím obsah uvnitř tohoto makra.

**Comment by repli2dev** [comment]
@klusidy  můžu to zavřít? Příčinu jsme IMHO našli.

**Comment by repli2dev** [comment]
Zavírám, případně založte nový task, pokud problém někde přetrvává.
