### ISSUE TITLE
Bezestavové SSO

### ISSUE THREAD

**Issue by repli2dev** [InstruktoriBrno/tmou-web#57]
Strávený čas:

2 hodiny (21. října 2019)

**Comment by miiila** [comment]
V JWT tokenu potřebuju kromě nějaké expiration, která může být dlouhá (a hlavně stejná, jako session) ještě název týmu a id týmu. Nic jiného by doufám nemělo být potřeba.

**Comment by repli2dev** [comment]
Je to nasazeno... Víc informací v README.md, víceméně jde o rozšíření předchozího systému... vzhledem k bezestavosti a tudíž praktické neinvalidovatelnosti jsem dal délku platnosti na 2 dny, poté by mělo stačit přistoupit na stránku.

Klíč je v lokálním konfigu.
