### ISSUE TITLE
Ročníky

### ISSUE THREAD

**Issue by repli2dev** [InstruktoriBrno/tmou-web#6]
V systému bude typ ročník s následujícími parametry:
- Motto
- Název
- Pořadové číslo ("tmou 20")
- Příznak zda má kvalifikaci, nebo ne.
- ~Příznak zda je termín kvalifikace už určen~ (půjde určit z nepřítomnosti obou hodnot)
- Datum začátku kvalifikace
- Datum konce kvalifikace
- ~Příznak zda je termín hry už určen~ (půjde určit z nepřítomnosti obou hodnot)
- Datum začátku hry
- Datum konce hry
- Počet týmů, kteří se do hry dostávají skrze kvalifikaci (pokud není, pak je to neomezeno, musí být menší než celkový počet týmů, je-li zadán)
- Počet týmů, kteří se tohoto ročníků může účeastnit (není vynucováno, jde spíše o prezentační číslo, organizátoři budou moci registrovat týmy i nad rámec)

Ročníky se spravují v gridu ročníků, kde je lze přidávat, upravovat a mazat.

Strávený čas:
- 4h (3. 5. 2019)

**Comment by klusidy** [comment]
Přidat entry na limit počtu týmů, které postupují z kvalifikace a počet divokých karet/celkový limit týmů

**Comment by repli2dev** [comment]
@klusidy dobrý nápad, přidám počet týmů pro kvalifikaci a počet týmů celkem... (viz úprava).
