### ISSUE TITLE
Nastavit jako hrající a zaplaceno

### ISSUE THREAD

**Issue by repli2dev** [InstruktoriBrno/tmou-web#77]

**Comment by miiila** [comment]
Nevzpomínám si, o co přesně tady šlo, můžeš mi to připomenout?

**Comment by repli2dev** [comment]
Jde o to, že ve skupinových akcích v seznamu týmů bylo potřeba provádět nejprve Zaplaceno a poté Hrající, takže toto mělo být zjednodušení tohoto procesu.

**Comment by miiila** [comment]
Nice to have

**Comment by repli2dev** [comment]
Provedeno.
