### ISSUE TITLE
Přidat podporu pro Travis CI

### ISSUE THREAD

**Issue by repli2dev** [InstruktoriBrno/tmou-web#8]
Shodli jsme se s @yaqwsx že chceme kontrolu statickou analýzou a code style pomocí Travis CI.

Licenci máme open (#7), takže by mělo jít o to v GitHub Marketspace ji povolit na organizaci (případně tomto repozitáři), k čemuž nemám oprávnění.

**Comment by yaqwsx** [comment]
Právě jsem přidal oprávnění, takže by mělo stačit přidat `.travis.yml`.

**Comment by repli2dev** [comment]
Funguje, zavírám.
