### ISSUE TITLE
Vyřešit odhlašování po 30 minutách

### ISSUE THREAD

**Issue by repli2dev** [InstruktoriBrno/tmou-web#81]
... Debian maže session storage automaticky po 30 minutách, ačkoliv platnost session je delší...

**Comment by miiila** [comment]
Bump, tohle bychom určitě chtěli vyřešit, loni to byl docela problém.

**Comment by repli2dev** [comment]
Tohle IMHO bude konfigurací serveru, takže to bude relevantní po #88.

**Comment by repli2dev** [comment]
Tohle bude zřejmě ta klasická věc, že sessions v debianu jsou mazány cronem `/etc/cron.d/php` (https://serverfault.com/questions/511609/why-does-debian-clean-php-sessions-with-a-cron-job-instead-of-using-phps-built),

Takže po otestování, že se to děje i na novém serveru to pak bude potřeba nějak vyřešit.

**Comment by repli2dev** [comment]
Otestoval jsem to 2x na novém serveru a problém se mi (už) neděje -- přihlpášení drží (jednou přes noc, jednou 1.5 hodiny), takže prosím otestujte i vy a pak zavřete.

**Comment by miiila** [comment]
👀

**Comment by miiila** [comment]
Zdá se, že funguje.
