### ISSUE TITLE
Kontrola a úprava bezstavového SSO

### ISSUE THREAD

**Issue by miiila** [InstruktoriBrno/tmou-web#87]
Pro upravené webinfo a pro novou kvalifikaci budeme chtít malinko jiný způsob ověření přihlášení. Zůstane podobně bezstavový, ale možná budeme potřebovat nějaký export tajné fráze, možná i její generování.

Úvaha je taková, že týmy budou přistupovat na `https://webinfo.tmou.cz/tajnafrazemehotymu` a nic jiného nebude třeba. Jako doteď se při loginu může vytvořit JWT, kam se přidá jedna položka nebo se fráze můžou vyexportovat těsně před hrou/kvalifikací.

Tuto issue nechávám jako placeholder pro diskusi a následnou implementaci, rozhodně výše uvedené není kompletní řešení problému.

**Comment by repli2dev** [comment]
Je to dost fundamentální snížení bezpečnosti, protože věci v GET jsou viditelné, zůstávají v browserech. Zbytek je na diskuzi.

**Comment by miiila** [comment]
Zatím možné ignorovat.

**Comment by repli2dev** [comment]
Note to myself:
* ověřit že jde mít více JWT tokenů na tým.
* ověřit že se v JWT tokenu předává ročník, aby to šlo rozlišit na třetí straně.
