### ISSUE TITLE
Přemigrovat na nový instruktorský server.

### ISSUE THREAD

**Issue by repli2dev** [InstruktoriBrno/tmou-web#88]

**Comment by repli2dev** [comment]
Bude vyžadovat přechod na PHP 7.4 (neměl být problém, stačí ověřit případně aktualizovat zastaralé knihovny) + úprava docker kompozice pro lokální spuštění.

Strávený čas: 6h

**Comment by repli2dev** [comment]
Upravil jsem Docker tooling a pak zvedl knihovny a utility, které měli s PHP 7.4 problém, rámcově to tedy běží, jen to na konci změn bude vhodné jako celek přetestovat.

**Comment by repli2dev** [comment]
Považuji za vyřešené.

@miiila otestujte co uznáte za vhodné a pak toto uzavřete.

**Comment by miiila** [comment]
Nechal bych to chíli otevřené, jakse se budou regitrovat týmy a pak bych to zavřel.

@repli2dev Projdi prosím v hlavně vše kolem synchronizace plateb a emailů (jeden jsem teď úspěšně poslal), tam to neumím dobře otestovat.

**Comment by repli2dev** [comment]
Zaregistroval jsem svůj tým, a v posledním týdnu se zaregistrovala i cca 10 dalších. Párovač na platby se spouští, ale zatím nemá co párovat (tohle zkontroluji ještě až platby začnou). E-maily chodí skrze webserver i skrze Mailgun.

Takže tenhle task zavírám.
