### ISSUE TITLE
Dockerizace

### ISSUE THREAD

**Issue by repli2dev** [InstruktoriBrno/tmou-web#9]
Protože #2 požaduje použití Keycloaku, bude jednoduší mít lokální nasazení pomocí Dockeru, ať není potřeba zdlouhavě konfigurovat a přidávat uživatele.

Rozsah:
- Apache + PHP 7.1 kontejner s použitelným Xdebug
- MariaDB 10.1 kontejner
- Adminer kontejner (nahradí vložený Adminer)
- Keycloak se základním množstvím uživatelů a nakonfigurovaný pro TMOU přihlášení

Strávený čas:
- 2 h (15. 4. 2019)
- 1h 30m (18. 4. 2019)

**Comment by yaqwsx** [comment]
Může být.

**Comment by repli2dev** [comment]
Samotná dockerizace je připravena, trochu vzdoruje jen Keyclock do kterého zatím umím naimportovat realm (~ scope) a uživatele, ale bez e-mailů a přiřazení do skupin.

**Comment by repli2dev** [comment]
Dokončeno, je to k otestování v rámci !10
