### ISSUE TITLE
Optimalizovat velikost pozadí

### ISSUE THREAD

**Issue by miiila** [InstruktoriBrno/tmou-web#90]
png na pozadí má asi 350Kb, bylo by fajn ho zmenšit.

**Comment by repli2dev** [comment]
Obrázek je celkem rozměrově veliký (3840x2160) a má aktuálně 364 KB...

TinyPNG už bylo aplikováno a nepomůže vůbec.
JPG a TinyJPG to dokáží dostat na cca 250 KB, což taky není žádná sláva.
GIF jsem zkoušel, ale vypadá to, že je tam použito stínování, tak to akorát obrázek zvětšuje.

U @yaqwsx jsem poptal jestli máme SVG.

Další možnosti jsou výrazně obrázek zmenšit (šířka a výška) a vybodnout se tak na kvalitní zobrazení na některých zařízeních.

**Comment by repli2dev** [comment]
@yaqwsx  mi poslal AI z čehož jsem zkusil vyexportovat a minimalizovat SVG (1.7 MB, po ZIP kompresi 1.6 MB) a PNG s 256 paletou, což použilo dither (pixelování k dosažení specifických přechodů) to ale udělal 1.2 MB soubor po kompresi v tinyPNG 1 MB. Tudy teda cesta nepovede.

Moje idea je tedy vygenerovat cca 3 velikosti a podle screeny pak načítat ty. Zmenší se to pro mobily dost výrazně, ale na velkých monitorech to také bude fungovat... a přejít na JPG v dostatečné kvalitě.

**Comment by miiila** [comment]
@repli2dev Souhlasím s různými velikostmi a pozadím podle media queries.

**Comment by repli2dev** [comment]
Provedeno... je tam JPEG pro velikosti do FULL HD, dál už je úspornější původní PNG.
