### ISSUE TITLE
Prezentace výsledků

### ISSUE THREAD

**Issue by miiila** [InstruktoriBrno/tmou-web#91]
Výsledky (https://www.tmou.cz/21/page/game-flow) se nevejdou na stránku, špatně se v nich scrolluje, přetékají... Pokud to bude možné, bylo by fajn to zlepšit.

**Comment by repli2dev** [comment]
Tohle byla dost bitva... nakonec je na to potřeba JS a je v tom jistý kompromis.

Do 800px výšky (1280x800) se zobrazuje stav jako dosud, s drobnou úpravou, která zajišťuje, že je fixován první jeden až dva sloupce (pokud si do tabulky přidáte třídu `table.stick-2-left-columns` nebo `table.stick-1-left-columns`). Bez nastavení pevné výšky neumím fixovat i hlavičku, což ale nevadí dokud se každých N výsledků opakuje standardní hlavička.

Pod 800px výšky se přepne celý obalující `.table-responsive` div do šířky počítané jako `100vh - výška hlaviček a bordelu`, tzn. tak aby se celý ten div vešel do viewportu když si uživatel vhodně nascroluje. V rámci toho je pak zafixovaná hlavička i ony sloupce, viz nahoře.

Za mě je to vyřešené, jiné optimalizace na to IMHO velmi pravděpodobně nevymyslíme, protože bojujeme s overflow nadřazenými boxy, parallaxem atp.
