### ISSUE TITLE
Poskakování při psaní v inputech/textareách

### ISSUE THREAD

**Issue by repli2dev** [InstruktoriBrno/tmou-web#93]
Děje se mi to ve FF, při stisku klávesy se nafokusuje vršek stránky, děje se to i na aktuální produkci.

**Comment by repli2dev** [comment]
@miiila přesto že jsem si dost jistý, že tohle issue bylo reprodukovatelné když jsem ho vytvářel, tak teď není, a to ani ve FF ani Chrome...

Prosím ověřit a případně zavřít.

**Comment by miiila** [comment]
Nedaří se mi to reprodukovat, takže zavírám.
