### ISSUE TITLE
Počet příspěvků ve vlákně

### ISSUE THREAD

**Issue by repli2dev** [InstruktoriBrno/tmou-web#96]
Zvážit jestli to tam nechceme na seznam vláken někam dát, víceméně to vyjadřuje jak je vlákno "horké", což některé lidi přitáhne a některé odradí.

**Comment by miiila** [comment]
Tohle se mi docela líbí, ale taky to je asi trochu nižší priorita než zobrazení výsledků.

**Comment by miiila** [comment]
@repli2dev Odhadni prosím, kolik by to zabralo/stálo.

**Comment by repli2dev** [comment]
Do 30 minut.

**Comment by repli2dev** [comment]
Provedeno.
