### ISSUE TITLE
Permalink na diskuzní příspěvky

### ISSUE THREAD

**Issue by repli2dev** [InstruktoriBrno/tmou-web#97]
Zvážit podporu možnosti přímého odkazu na příspěvek (jednak po kliknutí na  něco někde buď zkopírovat do schránky nebo aspoň narvat do adresného řádku, jednak je potřeba spravit focus v mobilních zobrazeních, kde zavazí hlavička).

**Comment by miiila** [comment]
Užitečné, ale asi to nemá prioritu.

**Comment by miiila** [comment]
@repli2dev Odhadni prosím, kolik by to zabralo/stálo.

**Comment by repli2dev** [comment]
Kvuli nutnosti vyresit ten posun pri zobrazeni hlavicky je toto cca 30-60 minut.

**Comment by repli2dev** [comment]
Provedeno.
